# Generated by Django 3.2.6 on 2021-09-04 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2, verbose_name='Gender')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars', verbose_name='avatar')),
                ('phone_number', models.PositiveBigIntegerField(unique=True, verbose_name='phone number')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
