# Generated by Django 3.2.6 on 2021-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Phone Number'),
        ),
    ]
