# Generated by Django 3.2.6 on 2021-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(max_length=100, verbose_name='Brand Link'),
        ),
    ]
