# Generated by Django 3.2.6 on 2021-09-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0003_auto_20210903_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webcrawlers.brand'),
        ),
    ]
