# Generated by Django 3.2.6 on 2021-09-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Product Brand'),
        ),
    ]
