# Generated by Django 3.2.6 on 2021-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Brand Name'),
        ),
    ]
