# Generated by Django 3.2.6 on 2021-09-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0006_alter_brand_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'url', 'new')},
        ),
    ]
