# Generated by Django 3.2.6 on 2021-09-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0008_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'url')},
        ),
    ]
