# Generated by Django 3.2.6 on 2021-09-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0009_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'url', 'new')},
        ),
    ]
