# Generated by Django 3.2.6 on 2021-09-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0010_alter_brand_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'url')},
        ),
    ]
