# Generated by Django 3.2.6 on 2021-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0011_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Brand Link'),
        ),
    ]
