# Generated by Django 3.2.6 on 2021-09-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0012_alter_brand_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text='In Dollars', max_length=50, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(verbose_name='Product URL'),
        ),
    ]
